name: Deploy to Vercel (Production)

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - production
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Minify JavaScript with Terser
        run: |
              npm terser ./app/js/prerender.js   --name-cache /tmp/cache.json  -o ./app/js/prerender.js
              npm terser ./app/js/postrender.js   --name-cache /tmp/cache.json  -o ./app/js/postrender.js
              npm terser ./app/js/main.js   --name-cache /tmp/cache.json  -o ./app/js/main.js
              npm terser ./app/js/item.js   --name-cache /tmp/cache.json  -o ./app/js/item.js
              npm terser ./app/serviceworker.js -o ./app/serviceworker.js
              npm terser ./app/item/storage.js   --name-cache /tmp/cache.json -o ./app/item/storage.js
      - name: Upload Minified Artifact
        uses: actions/upload-artifact@v2
        with:
          name: minified-artifact
          path: dist
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
