name: Deploy to Vercel (Production)

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - production
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Empty File
        run: touch cache.json
      - name: Install dependencies
        run: npm install terser -g
      - name: Minify JavaScript with Terser
        run: |
              terser ./app/js/prerender.js   --name-cache cache.json --mangle --mangle-props keep_quoted -o ./app/js/prerender.js
              terser ./app/js/postrender.js   --name-cache cache.json --mangle-props keep_quoted -o ./app/js/postrender.js
              terser ./app/js/main.js   --name-cache cache.json --mangle-props keep_quoted -o ./app/js/main.js
              terser ./app/js/item.js   --name-cache cache.json --mangle-props keep_quoted -o ./app/js/item.js
              terser ./app/serviceworker.js -o ./app/serviceworker.js
              terser ./app/item/storage.js   --name-cache cache.json -o ./app/item/storage.js
      - name: Upload Minified Artifact
        uses: actions/upload-artifact@v2
        with:
          name: minified-artifact
          path: .
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Extract Minified Artifacts
        run: |
          vercel --token=${{ secrets.VERCEL_TOKEN }} --prod
