name: Deploy Firebase Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'Test'

    steps:
      - name: 'Checkout repository' 
        uses: actions/checkout@v2

      - name: 'Deploy to Firebase'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_13301 }}'
          channelId: live
          projectId: portfolio-13301
 
  
