name: Deploy Firebase Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: alukasiewicz-artifact
        path: .
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    environment: 'Test'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: alukasiewicz-artifact
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
         uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}