name: Deploy Firebase Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "item/production-items.js"
        target: "item/items.js"
  deploy:
    runs-on: ubuntu-latest
    environment: 'Production'

    steps:
      - name: 'Checkout repository' 
        uses: actions/checkout@v2

      - name: 'Deploy to Firebase'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_13301 }}'
          channelId: live
          projectId: portfolio-13301
 
  
