name: Deploy on commit - Azure, Firebase

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'alukasiewicz'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F4C1D4F6DF984E37B646AC53F147CF61 }}
          package: .

      - name: 'Checkout repository' 
        uses: actions/checkout@v2

      - name: 'Deploy to Firebase'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_13301 }}'
          channelId: live
          projectId: portfolio-13301
 
  