name: Deploy Firebase Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout reporitory
      uses: actions/checkout@master
    - name: Copy production items
      uses: canastro/copy-file-action@master
      with:
        source: "item/production-items.js"
        target: "item/items.js"
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: alukasiewicz-artifact
        path: .
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: 'Test'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: alukasiewicz-artifact
          path: .
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_13301 }}
 
  
